version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: petclinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petclinic-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: petclinic-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - petclinic-net

volumes:
  mysql_data:

networks:
  petclinic-net:
